### ISSUE TITLE
No next page or page numbers

### ISSUE THREAD

**Issue by balagopal99** [lswlc33/Onemanager_theme_new_onedrive#2]
I have a folder with more than 200 items and so cannot see all my files because there is no page number available at the bottom.

Sorry for language as I only know english.

**Comment by lswlc33** [comment]
I will fix it today

**Comment by balagopal99** [comment]
Thank You
Kindly fix the issue in O-Material 3 theme as well

**Comment by lswlc33** [comment]
> Thank You Kindly fix the issue in O-Material 3 theme as well

All done
